### ISSUE TITLE
Retry on NoRouteToHostException

### ISSUE THREAD

**Issue by rfrovarp** [jhalterman/lyra#26] opened 2013-12-20 19:39 UTC
In our environment, it is entirely possible for systems to be trying to connect to our RabbitMQ server, while the server itself is down. Trying a new connection to a system that is powered off results in a NoRouteToHostException. In our case it would certainly make sense for that to be a retryable error.

**Comment by sergeyleyko** [comment] 2015-08-28 12:58
Vary sad, because it is often reproducible when servers with rabbit just restarted on amazon ec2.

**Comment by michaelklishin** [comment] 2015-08-28 13:13
@jhalterman while `NoRouteToHostException` is clearly an infrastructure-level issue, I wonder if it's worth making it re-triable, possibly as an option. It is indeed correct that on AWS, when instances are restarted or autoscaling group adds new ones, routing can be temporarily interrupted. AWS is an 800 pound gorilla in the infra room, so may be worth making an exception for.

@sergeyleyko what do you use for the hostname parameter, private IPs or private DNS? Public DNS?

**Comment by sergeyleyko** [comment] 2015-08-28 13:19
@michaelklishin we use just custom DNS name assigned to EC2 instance. (not Public DNS generated by AWS).
@jhalterman by the way, I cannot find the way to add this No route to host Exception to retryableExceptions list in config.

**Comment by michaelklishin** [comment] 2015-08-28 13:21
@sergeyleyko so your DNS is not managed by AWS in any way?

**Comment by sergeyleyko** [comment] 2015-08-28 13:24
@michaelklishin Yes, it is managed by 3rd party service. Just pointed to ec2 instance

**Comment by michaelklishin** [comment] 2015-08-28 13:26
@sergeyleyko then this is not AWS-specific. Still, I think it's reasonable to expect `NoRouteToHostException` to be re-triable in my opinion.

**Comment by sergeyleyko** [comment] 2015-08-28 13:34
@michaelklishin you are right. by the way, to add exception just use config.getRecoverableExceptions().add(newExceptionToRecover)

**Comment by jhalterman** [comment] 2015-08-28 15:35
@sergeyleyko If NoRouteToHost actually is recoverable, I'm fine with adding it to the default list. Curious: how long does it usually take to recover after a restart and a NoReouteToHostException?

**Comment by numbat** [comment] 2016-02-03 04:22
@jhalterman I was wondering if adding NoRouteToHostException is going to be added to the default list (or is this something that we can edit?). We're getting this issue on a deployment where the RabbitMQ instance goes down briefly each night and right now we have to do a corresponding restart of our services using Lyra on ubuntu instances.

**Comment by jhalterman** [comment] 2016-02-03 04:25
@numbat Super tied up on other projects at the moment. Two options:

* Add the exception via `config.getRecoverableExceptions().add(newExceptionToRecover)`
* Send me a quick pull request to get this added permanently. I believe the place to add it is here: https://github.com/jhalterman/lyra/blob/master/src/main/java/net/jodah/lyra/config/Config.java#L29

**Comment by numbat** [comment] 2016-02-03 04:32
Cheers will do, thanks!

**Comment by michaelklishin** [comment] 2017-10-04 11:14
Was addressed in 99ca312f4acd8de49e292ff3dabd3ae33c4bd287.

**Closed by michaelklishin** 2017-10-04 11:14 UTC
